##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. See MIT ile in
## the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_gen_core
description: A package that provides core utilities for practical code generation.
version: 0.2.1
repository: https://github.com/robmllze/df_gen_core

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.1.3
  df_config: ^0.1.1
  df_log: ^0.1.2
  df_string: ^0.1.1
  df_type: ^0.1.3

  analyzer: ^6.8.0
  args: ^2.5.0
  collection: ^1.19.0
  equatable: ^2.0.5
  http: ^1.2.2
  meta: ^1.15.0
  path: ^1.9.0
  source_gen: ^1.5.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
