##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_gen_core
description: A package that provides core utilities for practical code generation.
version: 0.4.5
repository: https://github.com/robmllze/df_gen_core
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - source-gen
  - build-runner
  - code-generation
  - utility
  - tool

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.8.3
  df_config: ^0.5.3
  df_log: ^0.2.4
  df_string: ^0.2.3
  df_type: ^0.7.2

  analyzer: ^6.11.0
  args: ^2.6.0
  equatable: ^2.0.5
  http: ^1.2.2
  meta: ^1.16.0
  path: ^1.9.1
  source_gen: ^1.5.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.1.0
